/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Classes.Departamento;
import Classes.Funcionario;
import DAO.DepartamentoDAO;
import DAO.FuncionarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author igor_
 */
public class Principal extends javax.swing.JFrame {
  
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbl_dep_dpts.getModel();
        DefaultTableModel funcionario = (DefaultTableModel) tbl_fun_funs.getModel();
        tbl_dep_dpts.setRowSorter(new TableRowSorter(modelo));
        tbl_fun_funs.setRowSorter(new TableRowSorter(funcionario));
        
        readJTable();
        readJTableFunc();
        
        btn_dep_salvar.setEnabled(false);
        btn_dep_cancelar.setEnabled(false);
        btn_dep_editar.setEnabled(false);
        btn_dep_excluir.setEnabled(false);
        btn_fun_salvar.setEnabled(false);
        btn_fun_cancelar.setEnabled(false);
        btn_fun_editar.setEnabled(false);
        btn_fun_excluir.setEnabled(false);
        c_dep_nome.setEnabled(false);
        c_dep_descricao.setEnabled(false);
        c_fun_nome.setEnabled(false);
        c_fun_cpf.setEnabled(false);
        c_fun_departamento.setEnabled(false);
        
        DepartamentoDAO dao = new DepartamentoDAO();
        
        for(Departamento d: dao.read()){
            c_fun_departamento.addItem(d);
        }
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) tbl_dep_dpts.getModel();
        modelo.setNumRows(0);
        DepartamentoDAO ddao = new DepartamentoDAO();
        
        for(Departamento d: ddao.read()){
            
            modelo.addRow(new Object[]{
                d.getCodigo(),
                d.getNome(),
                d.getDescricao()
            });
            
        }
    }
    
    public void readJTableFunc(){
        DefaultTableModel funcionario = (DefaultTableModel) tbl_fun_funs.getModel();
        funcionario.setNumRows(0);
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for(Funcionario f: fdao.read()){
            
            funcionario.addRow(new Object[]{
                f.getCodigo(),
                f.getDepartamento_id(),
                f.getNome(),
                f.getCpf()
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dep_dpts = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_dep_nome = new javax.swing.JTextField();
        btn_dep_salvar = new javax.swing.JButton();
        btn_dep_cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        c_dep_descricao = new javax.swing.JTextField();
        btn_dep_editar = new javax.swing.JButton();
        btn_dep_novo = new javax.swing.JButton();
        btn_dep_excluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_fun_funs = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        c_fun_nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_fun_cpf = new javax.swing.JTextField();
        btn_fun_salvar = new javax.swing.JButton();
        btn_fun_cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_fun_editar = new javax.swing.JButton();
        c_fun_departamento = new javax.swing.JComboBox<>();
        btn_fun_novo = new javax.swing.JButton();
        btn_fun_excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_dep_dpts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dep_dpts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dep_dptsMouseClicked(evt);
            }
        });
        tbl_dep_dpts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_dep_dptsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_dep_dpts);
        if (tbl_dep_dpts.getColumnModel().getColumnCount() > 0) {
            tbl_dep_dpts.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbl_dep_dpts.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_dep_dpts.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastro de Departamento"));

        jLabel2.setText("Nome: ");

        c_dep_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dep_nomeActionPerformed(evt);
            }
        });

        btn_dep_salvar.setText("Salvar");
        btn_dep_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_salvarActionPerformed(evt);
            }
        });

        btn_dep_cancelar.setText("Cancelar");
        btn_dep_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_cancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("Descrição:");

        btn_dep_editar.setText("Atualizar");
        btn_dep_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_dep_descricao)
                            .addComponent(c_dep_nome)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_dep_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_dep_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dep_cancelar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_dep_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(c_dep_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dep_salvar)
                    .addComponent(btn_dep_cancelar)
                    .addComponent(btn_dep_editar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_dep_novo.setText("Novo");
        btn_dep_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_novoActionPerformed(evt);
            }
        });

        btn_dep_excluir.setText("Excluir");
        btn_dep_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_dep_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dep_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dep_excluir)
                    .addComponent(btn_dep_novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Departamentos", jPanel1);

        tbl_fun_funs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Departamento", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_fun_funs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_fun_funsMouseClicked(evt);
            }
        });
        tbl_fun_funs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_fun_funsKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_fun_funs);
        if (tbl_fun_funs.getColumnModel().getColumnCount() > 0) {
            tbl_fun_funs.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_fun_funs.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbl_fun_funs.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastro de Funcionário"));

        jLabel4.setText("Nome: ");

        jLabel5.setText("CPF: ");

        btn_fun_salvar.setText("Salvar");
        btn_fun_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fun_salvarActionPerformed(evt);
            }
        });

        btn_fun_cancelar.setText("Cancelar");
        btn_fun_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fun_cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Departamento:");

        btn_fun_editar.setText("Atualizar");
        btn_fun_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fun_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c_fun_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_fun_departamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(c_fun_nome)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_fun_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(btn_fun_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fun_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c_fun_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(c_fun_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(c_fun_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fun_cancelar)
                    .addComponent(btn_fun_salvar)
                    .addComponent(btn_fun_editar))
                .addContainerGap())
        );

        btn_fun_novo.setText("Novo");
        btn_fun_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fun_novoActionPerformed(evt);
            }
        });

        btn_fun_excluir.setText("Excluir");
        btn_fun_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fun_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_fun_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fun_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fun_excluir)
                    .addComponent(btn_fun_novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Funcionários", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dep_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_novoActionPerformed
        c_dep_nome.setText("");
        c_dep_descricao.setText("");
        
        btn_dep_salvar.setEnabled(true);
        btn_dep_cancelar.setEnabled(true);
        c_dep_nome.setEnabled(true);
        c_dep_descricao.setEnabled(true);
        btn_dep_editar.setEnabled(false);
    }//GEN-LAST:event_btn_dep_novoActionPerformed

    private void btn_dep_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_cancelarActionPerformed
        btn_dep_novo.setEnabled(true);
        btn_dep_salvar.setEnabled(false);
        btn_dep_cancelar.setEnabled(false);
        btn_dep_editar.setEnabled(false);
        btn_dep_excluir.setEnabled(false);
        c_dep_nome.setEnabled(false);
        c_dep_descricao.setEnabled(false);
    }//GEN-LAST:event_btn_dep_cancelarActionPerformed

    private void btn_dep_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_salvarActionPerformed
        Departamento d = new Departamento();
        DepartamentoDAO dao = new DepartamentoDAO();
        d.setNome(c_dep_nome.getText());
        d.setDescricao(c_dep_descricao.getText());
        
        dao.create(d);
        
        c_dep_nome.setText("");
        c_dep_descricao.setText("");
        
        readJTable();
        
        btn_dep_salvar.setEnabled(false);
        btn_dep_cancelar.setEnabled(false);
        btn_dep_editar.setEnabled(false);
        btn_dep_excluir.setEnabled(false);
        c_dep_nome.setEnabled(false);
        c_dep_descricao.setEnabled(false);
    }//GEN-LAST:event_btn_dep_salvarActionPerformed

    private void c_dep_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dep_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_dep_nomeActionPerformed

    private void btn_fun_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fun_salvarActionPerformed
        Funcionario f = new Funcionario();
        Departamento jbox = (Departamento) c_fun_departamento.getSelectedItem();
        FuncionarioDAO dao = new FuncionarioDAO();
        f.setDepartamento_id(jbox.getCodigo());
        f.setNome(c_fun_nome.getText());
        f.setCpf(c_fun_cpf.getText());
        
        dao.create(f);
        
        //c_fun_departamento.setText("");
        c_fun_nome.setText("");
        c_fun_cpf.setText("");

        readJTableFunc();
        
        btn_fun_salvar.setEnabled(false);
        btn_fun_cancelar.setEnabled(false);
        btn_fun_editar.setEnabled(false);
        c_fun_nome.setEnabled(false);
        c_fun_cpf.setEnabled(false);
        c_fun_departamento.setEnabled(false);
        
    }//GEN-LAST:event_btn_fun_salvarActionPerformed

    private void btn_fun_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fun_novoActionPerformed
        c_fun_nome.setText("");
        
        btn_fun_salvar.setEnabled(true);
        btn_fun_cancelar.setEnabled(true);
        btn_fun_editar.setEnabled(false);
        c_fun_nome.setEnabled(true);
        c_fun_cpf.setEnabled(true);
        c_fun_departamento.setEnabled(true);
    }//GEN-LAST:event_btn_fun_novoActionPerformed

    private void btn_fun_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fun_cancelarActionPerformed
        btn_fun_salvar.setEnabled(false);
        btn_fun_cancelar.setEnabled(false);
        btn_fun_novo.setEnabled(true);
        btn_fun_editar.setEnabled(false);
        btn_fun_excluir.setEnabled(false);
        c_fun_nome.setEnabled(false);
        c_fun_cpf.setEnabled(false);
        c_fun_departamento.setEnabled(false);
    }//GEN-LAST:event_btn_fun_cancelarActionPerformed

    private void btn_dep_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_editarActionPerformed
        if(tbl_dep_dpts.getSelectedRow() != -1){
            Departamento d = new Departamento();
            DepartamentoDAO dao = new DepartamentoDAO();
            d.setNome(c_dep_nome.getText());
            d.setDescricao(c_dep_descricao.getText());
            d.setCodigo((int)tbl_dep_dpts.getValueAt(tbl_dep_dpts.getSelectedRow(), 0));

            dao.update(d);

            c_dep_nome.setText("");
            c_dep_descricao.setText("");

            readJTable();
            
            btn_dep_excluir.setEnabled(false);
            btn_dep_editar.setEnabled(false);
            btn_dep_cancelar.setEnabled(false);
            c_dep_nome.setEnabled(false);
            c_dep_descricao.setEnabled(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um departamento para ser editado!");
        }
    }//GEN-LAST:event_btn_dep_editarActionPerformed

    private void tbl_dep_dptsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_dep_dptsKeyReleased
        
        if(tbl_dep_dpts.getSelectedRow() != -1){
            
            c_dep_nome.setText(tbl_dep_dpts.getValueAt(tbl_dep_dpts.getSelectedRow(), 1).toString());
            c_dep_descricao.setText(tbl_dep_dpts.getValueAt(tbl_dep_dpts.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_tbl_dep_dptsKeyReleased

    private void tbl_dep_dptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dep_dptsMouseClicked
        if(tbl_dep_dpts.getSelectedRow() != -1){
            c_dep_nome.setText(tbl_dep_dpts.getValueAt(tbl_dep_dpts.getSelectedRow(), 1).toString());
            c_dep_descricao.setText(tbl_dep_dpts.getValueAt(tbl_dep_dpts.getSelectedRow(), 2).toString());
        }
        
        c_dep_nome.setEnabled(true);
        c_dep_descricao.setEnabled(true);
        btn_dep_editar.setEnabled(true);
        btn_dep_cancelar.setEnabled(true);
        btn_dep_excluir.setEnabled(true);
        btn_dep_novo.setEnabled(false);
    }//GEN-LAST:event_tbl_dep_dptsMouseClicked

    private void tbl_fun_funsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_fun_funsMouseClicked
        if(tbl_fun_funs.getSelectedRow() != -1){
            c_fun_departamento.setSelectedItem(tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 1).toString());
            c_fun_nome.setText(tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 2).toString());
            c_fun_cpf.setText(tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 3).toString());
        }
        
        btn_fun_novo.setEnabled(false);
        btn_fun_editar.setEnabled(true);
        btn_fun_excluir.setEnabled(true);
        btn_fun_cancelar.setEnabled(true);
        c_fun_nome.setEnabled(true);
        c_fun_cpf.setEnabled(true);
        c_fun_departamento.setEnabled(true);
    }//GEN-LAST:event_tbl_fun_funsMouseClicked

    private void tbl_fun_funsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_fun_funsKeyReleased
        if(tbl_fun_funs.getSelectedRow() != -1){
            c_fun_departamento.setSelectedItem(tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 1).toString());
            c_fun_nome.setText(tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 2).toString());
            c_fun_cpf.setText(tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tbl_fun_funsKeyReleased

    private void btn_fun_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fun_editarActionPerformed
        if(tbl_fun_funs.getSelectedRow() != -1){
            Funcionario f = new Funcionario();
            Departamento jbox = (Departamento) c_fun_departamento.getSelectedItem();
            FuncionarioDAO fdao = new FuncionarioDAO();
            f.setDepartamento_id(jbox.getCodigo());
            f.setNome(c_fun_nome.getText());
            f.setCpf(c_fun_cpf.getText());
            f.setCodigo((int)tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 0));

            fdao.update(f);
            
            //c_fun_departamento.setText("");
            c_fun_nome.setText("");
            c_fun_cpf.setText("");

            readJTableFunc();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um funcionário para ser editado!");
        }
        
        btn_fun_novo.setEnabled(true);
        btn_fun_editar.setEnabled(false);
        btn_fun_excluir.setEnabled(false);
        btn_fun_cancelar.setEnabled(false);
        c_fun_nome.setEnabled(false);
        c_fun_cpf.setEnabled(false);
        c_fun_departamento.setEnabled(false);
        
    }//GEN-LAST:event_btn_fun_editarActionPerformed

    private void btn_dep_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_excluirActionPerformed
        if(tbl_dep_dpts.getSelectedRow() != -1){
            Departamento d = new Departamento();
            DepartamentoDAO dao = new DepartamentoDAO();
            
            d.setCodigo((int)tbl_dep_dpts.getValueAt(tbl_dep_dpts.getSelectedRow(), 0));

            dao.delete(d);

            c_dep_nome.setText("");
            c_dep_descricao.setText("");

            readJTable();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um departamento para ser excluído!");
        }
        
        c_dep_nome.setEnabled(false);
        c_dep_descricao.setEnabled(false);
        btn_dep_salvar.setEnabled(false);
        btn_dep_cancelar.setEnabled(false);
        btn_dep_editar.setEnabled(false);
        btn_dep_excluir.setEnabled(false);
        btn_dep_novo.setEnabled(true);
    }//GEN-LAST:event_btn_dep_excluirActionPerformed

    private void btn_fun_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fun_excluirActionPerformed
        if(tbl_fun_funs.getSelectedRow() != -1){
            Funcionario f = new Funcionario();
            FuncionarioDAO fdao = new FuncionarioDAO();
            
            f.setCodigo((int)tbl_fun_funs.getValueAt(tbl_fun_funs.getSelectedRow(), 0));

            fdao.delete(f);

            //c_fun_departamento.setText("");
            c_fun_nome.setText("");
            c_fun_cpf.setText("");

            readJTableFunc();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um funcionário para ser excluído!");
        }
        
        btn_fun_novo.setEnabled(true);
        btn_fun_salvar.setEnabled(false);
        btn_fun_cancelar.setEnabled(false);
        btn_fun_editar.setEnabled(false);
        btn_fun_excluir.setEnabled(false);
        c_fun_nome.setEnabled(false);
        c_fun_cpf.setEnabled(false);
        c_fun_departamento.setEnabled(false);
    }//GEN-LAST:event_btn_fun_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dep_cancelar;
    private javax.swing.JButton btn_dep_editar;
    private javax.swing.JButton btn_dep_excluir;
    private javax.swing.JButton btn_dep_novo;
    private javax.swing.JButton btn_dep_salvar;
    private javax.swing.JButton btn_fun_cancelar;
    private javax.swing.JButton btn_fun_editar;
    private javax.swing.JButton btn_fun_excluir;
    private javax.swing.JButton btn_fun_novo;
    private javax.swing.JButton btn_fun_salvar;
    private javax.swing.JTextField c_dep_descricao;
    private javax.swing.JTextField c_dep_nome;
    private javax.swing.JTextField c_fun_cpf;
    private javax.swing.JComboBox<Object> c_fun_departamento;
    private javax.swing.JTextField c_fun_nome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_dep_dpts;
    private javax.swing.JTable tbl_fun_funs;
    // End of variables declaration//GEN-END:variables
}
